* [32mmain[m
  master[m
  tutorial-cleanning[m
  v25.12[m
  [31mremotes/appa/main[m
  [31mremotes/appa/master[m
  [31mremotes/appa/tutorial-cleanning[m
  [31mremotes/origin/Dev[m
  [31mremotes/origin/DevPlasticity[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/Tutorial[m
  [31mremotes/origin/actuatorBranch[m
  [31mremotes/origin/bakpaul_new_registration_mechanism[m
  [31mremotes/origin/cleanning/clean_scenes[m
  [31mremotes/origin/cosseratExtension-review2[m
  [31mremotes/origin/cosseratExtention-review[m
  [31mremotes/origin/cosseratState[m
  [31mremotes/origin/dev_coaxial_beam_model[m
  [31mremotes/origin/dev_coaxial_beam_model_v2[m
  [31mremotes/origin/feature/comprehensive-improvements[m
  [31mremotes/origin/feature/cosserat-dependency[m
  [31mremotes/origin/feature/cosserat-in-global-frame[m
  [31mremotes/origin/feature/cosserat-tests[m
  [31mremotes/origin/feature/differentiability-refactor[m
  [31mremotes/origin/feature/differentiable-liegroups[m
  [31mremotes/origin/feature/doc-and-quality-improvements[m
  [31mremotes/origin/feature/hookeseraPCS-force-field-v2[m
  [31mremotes/origin/feature/improve-basecosserat-mapping[m
  [31mremotes/origin/feature/lie-groups[m
  [31mremotes/origin/feature/liegroup-based-mappings[m
  [31mremotes/origin/feature/liegroups-python-bindings[m
  [31mremotes/origin/feature/liegroups-sola-improvements[m
  [31mremotes/origin/feature/plugin-reorganization[m
  [31mremotes/origin/feature/reorganize-python-bindings[m
  [31mremotes/origin/fixLinkWithSoftRobot[m
  [31mremotes/origin/guillaume_Samain[m
  [31mremotes/origin/hugtalbot-patch-1[m
  [31mremotes/origin/hugtalbot-patch-2[m
  [31mremotes/origin/hugtalbot-patch-3[m
  [31mremotes/origin/main[m
  [31mremotes/origin/master[m
  [31mremotes/origin/needleModule[m
  [31mremotes/origin/pr-add-tests[m
  [31mremotes/origin/pr-minor-fix-warnings[m
  [31mremotes/origin/pr-refactor-step3[m
  [31mremotes/origin/pr-synchronize-with-sofa-master[m
  [31mremotes/origin/refactor-src-organization[m
  [31mremotes/origin/refactor/mapping-components-cleanup[m
  [31mremotes/origin/revert-38-cosseratState[m
  [31mremotes/origin/testForVincent[m
  [31mremotes/origin/tutorial-june-2025[m
  [31mremotes/origin/update_python_prefabs[m
  [31mremotes/origin/update_python_prefabs_w_master_chpick_pr-add-tests[m
  [31mremotes/origin/update_test_scenes[m
  [31mremotes/origin/updateversion[m
  [31mremotes/origin/v20.12[m
  [31mremotes/origin/v21.12[m
  [31mremotes/origin/v22.06[m
  [31mremotes/origin/v22.12[m
  [31mremotes/origin/v23.06[m
  [31mremotes/origin/v23.12[m
  [31mremotes/origin/v24.06[m
  [31mremotes/origin/v24.12[m
  [31mremotes/origin/v24.12_update_workflow[m
  [31mremotes/origin/v25.06[m
  [31mremotes/origin/v25.12[m
  [31mremotes/origin/v25.12_update_workflow[m
